version: '3.5'
services:
  api:
    build: ./
    hostname: flask-multimedia
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 9000:9000
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=9000
      - FLASK_DEBUG=1
      - AZURE_STORAGE_SECRET_KEY
      - AZURE_STORAGE_CONNECTION_STRING
      - AZURE_CONTAINER_NAME
      - DATABASE_URL=postgresql://multimedia-user:multimedia-password@multimedia-db/multimedia
      - LOG_DIR=/usr/src/app/logs
    depends_on:
      - database
    networks:
      - multimedia-network

  database:
    image: postgres:15.2-alpine
    hostname: multimedia-db
    container_name: multimedia-db
    environment:
      POSTGRES_PASSWORD: multimedia-password
      POSTGRES_USER: multimedia-user
      POSTGRES_DB: multimedia
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U \"multimedia-user\" -d multimedia'"
        ]
      interval: 5s
      timeout: 5s
      retries: 2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - multimedia-network

  pgadmin:
    image: dpage/pgadmin4:7.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'ti@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin-ti'
    ports:
      - 6060:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - multimedia-network


volumes:
  pgadmin-data:
  postgres-data:

networks:
  multimedia-network: